apiVersion: apps/v1
kind: Deployment
metadata:
  name: ret
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ret
  template:
    metadata:
      labels:
        app: ret
    spec:
      containers:
      - image: okteto.dev/ret:latest
        name: ret
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "a258e2b6-c4c0-42a7-9d93-84c0bce2972f"
        - name: Vless_Path
          value: "/vl555"
        - name: Vmess_UUID
          value: "a258e2b6-c4c0-42a7-9d93-84c0bce2972f"
        - name: Vmess_Path
          value: "/vm666"
        - name: Share_Path
          value: "/v2link"
